spring:
  application:
    name: pos-carts
server:
  port: 0


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: false
    fetchRegistry: false
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
